Algoritmo "VerificarMaioridade"
// 1. Declarar uma variável para armazenar a idade.
// 2. Solicitar ao usuário que digite a idade.
// 3. Verificar se a idade é maior ou igual a 18
// 4. Exibir uma mensagem indicando se a pessoa
//é maior de idade ou menor de idade

Var
   idade: inteiro

Inicio
   escreva("Digite sua idade: ")
   leia(idade)
   
   se idade >= 18 entao
   escreva("Você é maior de idade")
   senao
   escreva("Você é menor de idade")
   fimse




Fimalgoritmo