Algoritmo "Contar_de_1_a_10"
//1. Declarar uma variável para usar como contador.
//2. Inicializar a variável contador com o valor 1.
//3. Usar uma estrutura de repetição para contar de 1 a 10.
//4. Exibir os números de 1 a 10.
Var
     contador: inteiro

Inicio
     contador:= 1
     
     enquanto contador <= 10 faca
     escreva(contador)
     contador <- contador + 1
     fimenquanto
     
     
     

Fimalgoritmo